# Ejercicio 3

In [1]:
import numpy as np

i) Reproducir la matriz B

In [2]:
#Generamos una matriz con las caracteristicas pedidas
B = np.arange(0.4, 0.8, 0.01)
print(B, "\n")
#Le damos una segunda dimencion a la matriz
Matriz_B = np.reshape(B,(5,8))
print(Matriz_B, "\n")

[0.4  0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5  0.51 0.52 0.53
 0.54 0.55 0.56 0.57 0.58 0.59 0.6  0.61 0.62 0.63 0.64 0.65 0.66 0.67
 0.68 0.69 0.7  0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79] 

[[0.4  0.41 0.42 0.43 0.44 0.45 0.46 0.47]
 [0.48 0.49 0.5  0.51 0.52 0.53 0.54 0.55]
 [0.56 0.57 0.58 0.59 0.6  0.61 0.62 0.63]
 [0.64 0.65 0.66 0.67 0.68 0.69 0.7  0.71]
 [0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79]] 



ii) Unir B con el resultado del ejercicio anterior 2 para obtener una matriz de 8 lineas y 13 columnas.

In [15]:
#Pasamoss el procedimiento de la matriz del ejercicio 2
matriz1 = np.arange(1, 65, 1)
print(matriz1, "\n")
#con ell metoodo "reshape" le damos una segunda dimecion a la primera matriz (filas, columnas)
matriz2 = np.reshape(matriz1,(8,8))

# trassponemos la matriz para que las filas se conviertan en columnas
matriz_t = np.transpose(matriz2)

#Se crea 2 ciclos for en loss cuales corresponde el numero de filas y  columnas
for i in range(8):
  for j in range (8):
#Se porcedde a cambiar los valores de la matriz a variables string
    elemento = str(matriz2[i][j])
#Con el metodo "find" buscamos entre la matriz bidimencional el caracter 3
    cambio = elemento.find('3')
#Como el metodo "find" encuentra el caracter  3 lo cambia por un -1, 
#junto con el condiccional esto nor permite cambiar dicho caracter por un -99
    if (cambio != -1):
      matriz2[i][j] = -99

#Pasamos la matriz resultante del ejercicio anterior a una nueva por comodidad
Matriz_A = matriz2
print(Matriz_A, "\n")

#Una vez que ya tenemos ambas matrices procedemos a concaatenar ambas matriceZ
Matriz_AB = np.concatenate([Matriz_A, Matriz_B])
#Nos da de resultado una matriz de 13x8
print(Matriz_AB)

#Sacamos la traspuesta de la matriz paara obtener la matris de 8X13 
Matriz_C = np.transpose(Matriz_AB)
Matriz_C

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64] 

[[  1   2 -99   4   5   6   7   8]
 [  9  10  11  12 -99  14  15  16]
 [ 17  18  19  20  21  22 -99  24]
 [ 25  26  27  28  29 -99 -99 -99]
 [-99 -99 -99 -99 -99 -99 -99  40]
 [ 41  42 -99  44  45  46  47  48]
 [ 49  50  51  52 -99  54  55  56]
 [ 57  58  59  60  61  62 -99  64]] 

[[  1.     2.   -99.     4.     5.     6.     7.     8.  ]
 [  9.    10.    11.    12.   -99.    14.    15.    16.  ]
 [ 17.    18.    19.    20.    21.    22.   -99.    24.  ]
 [ 25.    26.    27.    28.    29.   -99.   -99.   -99.  ]
 [-99.   -99.   -99.   -99.   -99.   -99.   -99.    40.  ]
 [ 41.    42.   -99.    44.    45.    46.    47.    48.  ]
 [ 49.    50.    51.    52.   -99.    54.    55.    56.  ]
 [ 57.    58.    59.    60.    61.    62.   -99.    64.  ]
 [  0.4    0.41   0.42   0.43   0.44   0.45   0

array([[  1.  ,   9.  ,  17.  ,  25.  , -99.  ,  41.  ,  49.  ,  57.  ,
          0.4 ,   0.48,   0.56,   0.64,   0.72],
       [  2.  ,  10.  ,  18.  ,  26.  , -99.  ,  42.  ,  50.  ,  58.  ,
          0.41,   0.49,   0.57,   0.65,   0.73],
       [-99.  ,  11.  ,  19.  ,  27.  , -99.  , -99.  ,  51.  ,  59.  ,
          0.42,   0.5 ,   0.58,   0.66,   0.74],
       [  4.  ,  12.  ,  20.  ,  28.  , -99.  ,  44.  ,  52.  ,  60.  ,
          0.43,   0.51,   0.59,   0.67,   0.75],
       [  5.  , -99.  ,  21.  ,  29.  , -99.  ,  45.  , -99.  ,  61.  ,
          0.44,   0.52,   0.6 ,   0.68,   0.76],
       [  6.  ,  14.  ,  22.  , -99.  , -99.  ,  46.  ,  54.  ,  62.  ,
          0.45,   0.53,   0.61,   0.69,   0.77],
       [  7.  ,  15.  , -99.  , -99.  , -99.  ,  47.  ,  55.  , -99.  ,
          0.46,   0.54,   0.62,   0.7 ,   0.78],
       [  8.  ,  16.  ,  24.  , -99.  ,  40.  ,  48.  ,  56.  ,  64.  ,
          0.47,   0.55,   0.63,   0.71,   0.79]])

iii). Agregar una linea al final con el promedio de cada columna

In [76]:
promedio = np.zeros((1,13))

suma = 0
#Generamos un ciclo en el cual se iran sumando respectivamente todos los valores de las columnas para sacar su proomedio
for i in range(13):
    for j in range(8):
        suma = suma + Matriz_C[j][i]
    promedio[0][i] = suma/8

#Concatenamos la matriz de los promedio con la matriz c
Matriz_CPromedios = np.concatenate([Matriz_C, promedio])
print(Matriz_CPromedios)

[[   1.       9.      17.      25.     -99.      41.      49.      57.
     0.4      0.48     0.56     0.64     0.72 ]
 [   2.      10.      18.      26.     -99.      42.      50.      58.
     0.41     0.49     0.57     0.65     0.73 ]
 [ -99.      11.      19.      27.     -99.     -99.      51.      59.
     0.42     0.5      0.58     0.66     0.74 ]
 [   4.      12.      20.      28.     -99.      44.      52.      60.
     0.43     0.51     0.59     0.67     0.75 ]
 [   5.     -99.      21.      29.     -99.      45.     -99.      61.
     0.44     0.52     0.6      0.68     0.76 ]
 [   6.      14.      22.     -99.     -99.      46.      54.      62.
     0.45     0.53     0.61     0.69     0.77 ]
 [   7.      15.     -99.     -99.     -99.      47.      55.     -99.
     0.46     0.54     0.62     0.7      0.78 ]
 [   8.      16.      24.     -99.      40.      48.      56.      64.
     0.47     0.55     0.63     0.71     0.79 ]
 [  -8.25    -9.75    -4.5    -24.75  -106.375  

iv). Agregar una columna al final con el valor maximo de cada fila

In [89]:
valores = []
for l in Matriz_CPromedios:
    maximo = max(l)
    valores.append((maximo))
Valores_M = np.reshape(valores,(9,1))

MAtriz_Final = np.concatenate([Matriz_CPromedios,Valores_M], axis = 1)
print(MAtriz_Final)

[[57. ]
 [58. ]
 [59. ]
 [60. ]
 [61. ]
 [62. ]
 [55. ]
 [64. ]
 [-2.9]] 

[[   1.       9.      17.      25.     -99.      41.      49.      57.
     0.4      0.48     0.56     0.64     0.72    57.   ]
 [   2.      10.      18.      26.     -99.      42.      50.      58.
     0.41     0.49     0.57     0.65     0.73    58.   ]
 [ -99.      11.      19.      27.     -99.     -99.      51.      59.
     0.42     0.5      0.58     0.66     0.74    59.   ]
 [   4.      12.      20.      28.     -99.      44.      52.      60.
     0.43     0.51     0.59     0.67     0.75    60.   ]
 [   5.     -99.      21.      29.     -99.      45.     -99.      61.
     0.44     0.52     0.6      0.68     0.76    61.   ]
 [   6.      14.      22.     -99.     -99.      46.      54.      62.
     0.45     0.53     0.61     0.69     0.77    62.   ]
 [   7.      15.     -99.     -99.     -99.      47.      55.     -99.
     0.46     0.54     0.62     0.7      0.78    55.   ]
 [   8.      16.      24.    

v). Guardar el archivo

In [90]:
np.savetxt('datos.csv', MAtriz_Final, delimiter=',', fmt='%.3f', header="1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, max")